services:
  fake-oidc:
    build:
      context: .
    networks:
      - fulcio
    command: [ "fakeoidc"]
    restart: always # keep the server running
    ports:
      - "8080:8080"
    healthcheck:
      test: "curl -f http://localhost:8080/.well-known/openid-configuration"
      interval: 10s

networks:
  fulcio:
    name: fulcio_default
    external: true
