name: Test github action with TUF

on:
  pull_request:
    branches: [ main ]
    paths-ignore:
      - 'terraform/**'

defaults:
  run:
    shell: bash
    working-directory: ./

concurrency:
  group: test-github-action-with-tuf${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  test-github-action:
    name: Test github action with TUF
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false # Keep running if one leg fails.
      matrix:
        k8s-version:
          - v1.29.x
          - v1.30.x
          - v1.31.x
          - v1.32.x
        release-version:
          - "main" # Test explicitly with latest
        go-version:
          - 1.23.x
        leg:
          - test github action with TUF
    env:
      KO_DOCKER_REPO: registry.local:5000/knative

    steps:
    - name: Checkout scaffolding
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
    - name: Setup scaffolding
      run: |
        # This is a simplified copy of actions/setup/action.yml: the action cannot really deploy
        # from the current commit

        set -ex

        # Configure DockerHub mirror
        tmp=$(mktemp)
        if [ ! -f /etc/docker/daemon.json ]; then
          echo '{}' | sudo tee /etc/docker/daemon.json
        fi
        jq '."registry-mirrors" = ["https://mirror.gcr.io"]' /etc/docker/daemon.json > "$tmp"
        sudo mv "$tmp" /etc/docker/daemon.json
        sudo service docker restart

        echo "Installing kind and knative using setup-kind.sh from current commit"

        ./hack/setup-kind.sh \
          --registry-url registry.local:5000 \
          --cluster-suffix cluster.local \
          --k8s-version ${{ matrix.k8s-version }} ''

        ./hack/setup-scaffolding.sh

        TUF_MIRROR=$(kubectl -n tuf-system get ksvc tuf -ojsonpath='{.status.url}')
        echo "TUF_MIRROR=$TUF_MIRROR" >> $GITHUB_ENV
        # Grab the trusted root
        kubectl -n tuf-system get secrets tuf-root -ojsonpath='{.data.root}' | base64 -d > ./root.json

        # Make copy of the tuf root in the default namespace for tests
        kubectl -n tuf-system get secrets tuf-root -oyaml | sed 's/namespace: .*/namespace: default/' | kubectl create -f -

        REKOR_URL=$(kubectl -n rekor-system get ksvc rekor -ojsonpath='{.status.url}')
        FULCIO_URL=$(kubectl -n fulcio-system get ksvc fulcio -ojsonpath='{.status.url}')
        FULCIO_GRPC_URL=$(kubectl -n fulcio-system get ksvc fulcio-grpc -ojsonpath='{.status.url}')
        CTLOG_URL=$(kubectl -n ctlog-system get ksvc ctlog -ojsonpath='{.status.url}')
        ISSUER_URL=$(kubectl get ksvc gettoken -ojsonpath='{.status.url}')
        TSA_URL=$(kubectl -n tsa-system get ksvc tsa -ojsonpath='{.status.url}')

        # Grab an OIDC token too.
        OIDC_TOKEN=$(curl -s $ISSUER_URL)
        echo "OIDC_TOKEN=$OIDC_TOKEN" >> $GITHUB_ENV

        # And set the env variables for workflow visibility
        echo "REKOR_URL=$REKOR_URL" >> $GITHUB_ENV
        echo "FULCIO_URL=$FULCIO_URL" >> $GITHUB_ENV
        echo "FULCIO_GRPC_URL=$FULCIO_GRPC_URL" >> $GITHUB_ENV
        echo "CTLOG_URL=$CTLOG_URL" >> $GITHUB_ENV
        echo "ISSUER_URL=$ISSUER_URL" >> $GITHUB_ENV
        echo "TSA_URL=$TSA_URL" >> $GITHUB_ENV

    # Install cosign
    - name: Install cosign
      uses: sigstore/cosign-installer@d7d6bc7722e3daa8354c50bcb52f4837da5e9b6a # v3.8.1

    - name: Set up Go
      uses: actions/setup-go@f111f3307d8850f501ac008e886eec1fd1932a34 # v5.3.0
      with:
        go-version: ${{ matrix.go-version }}
        check-latest: true

    - uses: ko-build/setup-ko@d982fec422852203cfb2053a8ec6ad302280d04d # v0.8

    - name: Create sample image
      run: |
        pushd $(mktemp -d)
        go mod init example.com/demo-action-with-tuf
        cat <<EOF > main.go
        package main
        import "fmt"
        func main() {
          fmt.Println("hello world")
        }
        EOF
        demoimage=$(ko publish -B example.com/demo-action-with-tuf)
        echo "demoimage=$demoimage" >> $GITHUB_ENV
        echo Created image $demoimage
        popd

    - name: Initialize cosign with TUF root
      run: cosign initialize --mirror ${{ env.TUF_MIRROR }} --root ./root.json

    - name: Sign with cosign from the action using k8s token
      run: |
        cosign sign --yes --rekor-url ${{ env.REKOR_URL }} --fulcio-url ${{ env.FULCIO_URL }} --allow-insecure-registry ${{ env.demoimage }} --identity-token ${{ env.OIDC_TOKEN }}

    - name: Verify with cosign from the action using k8s token
      run: |
        cosign verify --rekor-url "${{ env.REKOR_URL }}" \
        --allow-insecure-registry "${{ env.demoimage }}" \
        --certificate-identity "https://kubernetes.io/namespaces/default/serviceaccounts/default" \
        --certificate-oidc-issuer "https://kubernetes.default.svc.cluster.local"

    - name: Sign and verify with signature bundle format and trusted root
      run: |
        cosign sign-blob --yes --new-bundle-format=true --bundle=bundle.json --rekor-url ${{ env.REKOR_URL }} --fulcio-url ${{ env.FULCIO_URL }} --identity-token ${{ env.OIDC_TOKEN }} README.md

        # TODO: drop --trusted-root when cosign actually uses trusted root by default
        cosign verify-blob \
            --certificate-identity-regexp="https://kubernetes.io/namespaces/default/serviceaccounts/default" \
            --certificate-oidc-issuer-regexp="https://kubernetes.default.svc.cluster.local" \
            --bundle=bundle.json  --new-bundle-format \
            --rekor-url $REKOR_URL \
            --trusted-root=$HOME/.sigstore/root/targets/trusted_root.json \
            README.md

    - name: Checkout TSA for testing.
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      with:
        repository: sigstore/timestamp-authority
        path: ./src/github.com/sigstore/timestamp-authority
    - name: Build timestamp-cli
      working-directory: ./src/github.com/sigstore/timestamp-authority
      run: |
        go build -o ./timestamp-cli ./cmd/timestamp-cli
    - name: Exercise TSA
      working-directory: ./src/github.com/sigstore/timestamp-authority
      run: |
        curl ${{ env.TSA_URL }}/api/v1/timestamp/certchain > ts_chain.pem
        echo "myblob" > myblob
        if ! ./timestamp-cli --timestamp_server ${{ env.TSA_URL }} timestamp --hash sha256 --artifact myblob --out response.tsr ; then
          echo "failed to timestamp artifact"
          exit -1
        fi
        if ! ./timestamp-cli verify --timestamp response.tsr --artifact "myblob" --certificate-chain ts_chain.pem ; then
          echo "failed to verify timestamp"
          exit -1
        fi
        if ! ./timestamp-cli inspect --timestamp response.tsr --format json ; then
          echo "failed to inspect the timestamp"
          exit -1
        fi

    - name: Collect diagnostics
      if: ${{ failure() }}
      uses: chainguard-dev/actions/kind-diag@main
